/* Automatically generated by configure - do not modify! */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H
#define FFMPEG_CONFIGURATION ""
#define FFMPEG_LICENSE "LGPL version 2.1 or later"
#define CONFIG_THIS_YEAR 2018
#define FFMPEG_DATADIR "/usr/local/share/ffmpeg"
#define AVCONV_DATADIR "/usr/local/share/ffmpeg"
#define CC_IDENT "gcc 4.8 (Ubuntu 4.8.5-4ubuntu2)"
#define av_restrict restrict
#define EXTERN_PREFIX ""
#define EXTERN_ASM 
#define SLIBSUF ".so"


#define HAVE_ALIGNED_MALLOC 0
#define HAVE_WINSOCK2_H 0
#define HAVE_THREADS 1

#define CONFIG_NETWORK 1
#define CONFIG_ZLIB 0

#define HAVE_POLL_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_STRERROR_R 1
#endif /* FFMPEG_CONFIG_H */
